model_list:
  - model_name: "*"
    litellm_params:
      model: openrouter/*
      api_key: os.environ/OPENROUTER_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  disable_master_key_return: true